---
title: "FHS_data_sum_tbl"
output: html_document
date: "2025-09-01"
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Setup
```{r}
library(tidyr)
library(plyr)
library(dplyr)
library(ggplot2)
library(mice)
library(glmnet)
library(class)
library(MASS)
library(factoextra)
library(mice)
library(VIM)
library(caret)
library(pROC)
library(Hmisc)
library(corrplot)
library(GGally)
library(compareGroups)
library(kableExtra)
library(knitr)
fhs_data <- read.csv('fhs_data.csv')
```

## Exploring repeat data
```{r}
nrow(fhs_data) #11627 observations

## counting the number of subjects
rand_ids <- plyr::count(fhs_data$RANDID)
rand_ids$subject_number <- 1:nrow(rand_ids)
length(unique(fhs_data$RANDID)) #4434 subjects


## showing how many subjects have more than 1 observation
(tbl_counts <- table(rand_ids$freq)) # 3206 subjects have 3 observations
(tbl_counts_prop <- tbl_counts / sum(tbl_counts)) # 72.3% have 3 observations

## counting the number of subjects we have in the dataset
length(unique(fhs_data$RANDID)) # 4434 subjects total

## reordering the dataset
fhs_data <- fhs_data[order(fhs_data$RANDID),]
# View(head(fhs_data[fhs_data$DEATH==1,]))
```

## Data-preprocessing

### Data filtering by most recent
```{r}
fhs_most_recent <- fhs_data %>%
  group_by(RANDID) %>%
  filter(PERIOD == max(PERIOD)) %>%
  ungroup()

nrow(fhs_most_recent)

fhs_most_recent <- fhs_most_recent[,c('RANDID','AGE','SEX','SYSBP','DIABP','TOTCHOL','HDLC','LDLC','GLUCOSE','CURSMOKE','CIGPDAY','HEARTRTE', 'educ', 'PREVCHD', 'PREVAP', 'PREVMI','PREVSTRK', 'PREVHYP', 'ANGINA', 'HOSPMI', 'MI_FCHD', 'STROKE', 'CVD', 'ANYCHD', 'HYPERTEN', 'BMI','DIABETES','BPMEDS','DEATH')]

# transforming binary variables into factors
fhs_most_recent <- fhs_most_recent %>%
  mutate(across(
    where(~ n_distinct(.) == 2), 
    as.factor
  ))
```

## Tallying up the missing values in each column
```{r}
library(gtsummary)
NA_tally <- unlist(lapply(fhs_most_recent, function(x){sum(is.na(x))/length(x)}))
NA_df <- data.frame('Column_Name' = names(NA_tally),
                    'Missing_Proportion' = round(unname(NA_tally),2))

NA_df <- NA_df[order(NA_df$Missing_Proportion, decreasing=T), ]
rownames(NA_df) <- NULL
View(NA_df)


NA_df %>%
  kbl(caption = "Table S1: Missingness by Column") %>%
  kable_classic(full_width = F, html_font = "Cambria")


# filter by variables that have 5% missing or less
v_names_use <- names(NA_tally)[NA_tally < 0.05]
v_names_use <- v_names_use[-1]
```

## Comparing Groups
```{r}
fhs_most_recent_red <- fhs_most_recent[,(colnames(fhs_most_recent) %in% v_names_use)]
# res <- compareGroups(DEATH~., data=fhs_most_recent_red)
# restab <- createTable(res, hide.no = "no")
# export2md(restab, caption = 'Table 1: Summary Statistics by Death Status', html_font = 'Cambria') %>% kable_classic(html_font = "Cambria")


tbl <- fhs_most_recent_red %>%
  tbl_summary(
    by = DEATH,                            # Grouping variable
    statistic = list(
      all_continuous() ~ "{mean} ({sd})", 
      all_categorical() ~ "{n} ({p}%)"
    ),
    type = list(all_categorical() ~ "categorical"),
    missing = "no"
  ) %>%
  add_p(test = list(
    all_continuous() ~ "t.test",        # t-test for continuous vars
    all_categorical() ~ "chisq.test"    # chi-sq for categorical vars
  )) %>%
  as_kable(extra_css = "style='width:100%;'", caption = "Table 1: Summary Statistics by DEATH") %>%
  kable_classic(full_width = F, html_font = "Cambria")

tbl
```

### Exporting as excel file
```{r}
library(openxlsx)
tbl2 <- fhs_most_recent_red %>%
  tbl_summary(
    by = DEATH,
    statistic = list(
      all_continuous() ~ "{mean} ({sd})",
      all_categorical() ~ "{n} ({p}%)"
    ),
    missing = "no"
  ) %>%
  add_p(test = list(
    all_continuous() ~ "t.test",
    all_categorical() ~ "chisq.test"
  ))

# Convert to a data frame
tbl_df <- as_tibble(tbl2)

# Write to Excel
write.xlsx(tbl_df, "summary_table1.xlsx")
```




